spring:
  application:
    name: product-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://root:java@mongodb:27017/productdb?authSource=admin

server:
  port: 7410

#aws  access-key  and secret-key
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ap-south-1



management:
  endpoints:
    web:
      exposure:
        include: '*'

  config:
    import: optional:configserver:http://localhost:1000
  cloud:
    bus:
      enabled: true  # Enable Spring Cloud Bus
  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


